import { Header } from '@/components/layout/header';

export const metadata = { title: 'Terms of Service — FitTrack Pro' };

export default function TermsPage() {
  const updated = 'May 4, 2026';

  return (
    <div className="min-h-screen">
      <Header title="Terms of Service" showBack />
      <div className="mx-auto max-w-2xl space-y-8 px-4 py-6 text-sm leading-relaxed text-muted-foreground">
        <p className="text-xs">Last updated: {updated}</p>

        <Section title="1. Acceptance of Terms">
          <p>
            By creating an account or using FitTrack Pro (&quot;the App&quot;, &quot;we&quot;, &quot;our&quot;), you agree to be bound by
            these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the App.
          </p>
        </Section>

        <Section title="2. Health & Medical Disclaimer">
          <p>
            <strong className="text-foreground">FitTrack Pro is not a medical service.</strong> The workout plans,
            nutrition targets, calorie recommendations, and AI coaching suggestions provided by the App are for
            general informational and motivational purposes only. They are not intended to constitute medical
            advice, diagnosis, or treatment.
          </p>
          <p className="mt-3">
            Always consult a qualified physician, healthcare provider, certified personal trainer, or registered
            dietitian before starting a new exercise or nutrition programme, particularly if you:
          </p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Have a pre-existing medical condition, injury, or disability</li>
            <li>Are pregnant, postpartum, or trying to conceive</li>
            <li>Are taking prescription medication</li>
            <li>Have not exercised regularly in the past 12 months</li>
            <li>Are under 18 years of age</li>
          </ul>
          <p className="mt-3">
            Stop exercising immediately and seek medical attention if you experience chest pain, severe shortness
            of breath, dizziness, fainting, or any other unusual symptom during exercise.
          </p>
          <p className="mt-3">
            <strong className="text-foreground">You exercise entirely at your own risk.</strong> FitTrack Pro and
            its developers accept no liability for injury, illness, or adverse outcomes arising from following
            recommendations generated by the App.
          </p>
        </Section>

        <Section title="3. AI-Generated Advice">
          <p>
            The App includes an AI coaching feature powered by Claude (Anthropic). AI responses are generated
            automatically and may not account for your complete personal circumstances. They are illustrative
            suggestions only and should not replace professional advice.
          </p>
          <p className="mt-3">
            We do not guarantee the accuracy, completeness, or suitability of any AI-generated content for your
            individual needs.
          </p>
        </Section>

        <Section title="4. Eligibility">
          <p>
            You must be at least 16 years old to use FitTrack Pro. By using the App you represent that you meet
            this requirement and have the legal capacity to enter into these Terms.
          </p>
        </Section>

        <Section title="5. Your Account">
          <p>
            You are responsible for maintaining the confidentiality of your login credentials and for all activity
            that occurs under your account. Notify us immediately of any unauthorised use.
          </p>
        </Section>

        <Section title="6. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Use the App for any unlawful purpose</li>
            <li>Attempt to access other users&apos; data</li>
            <li>Reverse-engineer or attempt to extract the source code of the App</li>
            <li>Submit false or misleading health information</li>
            <li>Use automated tools to scrape or overload the App</li>
          </ul>
        </Section>

        <Section title="7. Data & Privacy">
          <p>
            Our collection and use of your personal data is described in our{' '}
            <a href="/privacy" className="font-medium text-primary underline-offset-2 hover:underline">Privacy Policy</a>,
            which forms part of these Terms.
          </p>
        </Section>

        <Section title="8. Intellectual Property">
          <p>
            All content, algorithms, and design elements of the App are the intellectual property of FitTrack Pro
            and may not be reproduced without written permission.
          </p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>
            To the fullest extent permitted by applicable law, FitTrack Pro and its developers shall not be liable
            for any indirect, incidental, special, consequential, or punitive damages, including but not limited
            to personal injury, loss of data, or loss of profits, arising from your use of the App.
          </p>
          <p className="mt-3">
            Our total aggregate liability to you for any claim shall not exceed the amount you paid us in the
            12 months preceding the claim, or £50 (GBP), whichever is greater.
          </p>
        </Section>

        <Section title="10. Modifications">
          <p>
            We may update these Terms at any time. Continued use of the App after changes are posted constitutes
            acceptance of the updated Terms. We will notify you of material changes via the App or by email.
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms are governed by and construed in accordance with the laws of England and Wales. Any
            disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            For questions about these Terms, contact us at{' '}
            <a href="mailto:support@fittrackpro.app" className="font-medium text-primary underline-offset-2 hover:underline">
              support@fittrackpro.app
            </a>.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 text-base font-semibold text-foreground">{title}</h2>
      {children}
    </section>
  );
}
